name: Update 280blocker Filter

on:
  schedule:
    # 毎月1日の日本時間 正午（JST 12:05 ≒ UTC 03:05）に実行
    - cron: '5 3 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run updater
        run: python get_280blocker.py

      - name: Check for changes
        id: diff
        run: |
          if [[ -n "$(git status --porcelain adguard.txt)" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add adguard.txt
          git commit -m "Update 280blocker filter"
          git push
