- name: Fetch via Cloudflare Worker (root-first)
  run: |
    set -e
    BASE="https://block.shigelon.workers.dev"
    OK=""

    try_fetch () {
      URL="$1"
      echo "GET $URL"
      STATUS=$(curl -sS -w "%{http_code}" -o adguard.txt "$URL")
      echo "status=$STATUS"
      if [ "$STATUS" = "200" ] && [ -s adguard.txt ] && [ $(wc -c < adguard.txt) -ge 200 ]; then
        OK=1
      fi
    }

    # 1) まず ルート?nocache=1
    try_fetch "${BASE}/?nocache=1"
    # 2) ダメなら ルート
    if [ -z "$OK" ]; then try_fetch "${BASE}/"; fi
    # 3) それでもダメなら /latest?nocache=1
    if [ -z "$OK" ]; then try_fetch "${BASE}/latest?nocache=1"; fi
    # 4) 最後に /latest
    if [ -z "$OK" ]; then try_fetch "${BASE}/latest"; fi

    if [ -z "$OK" ]; then
      echo "=== Last response body ==="
      curl -sS "${BASE}/" || true
      exit 1
    fi
